MVC/Models/mvcItems.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class mvcItems
    {
        public int ItemID { get; set; }
        [Required(ErrorMessage = "Please Enter Item code...")]

        public string ItemCode { get; set; }
        [Required(ErrorMessage = "Please Enter Item Name...")]

        public string ItemName { get; set; }
        [Required(ErrorMessage = "Please Enter Item Price...")]

        public Nullable<double> Price { get; set; }

        public string Description { get; set; }
        [Required(ErrorMessage = "Please Enter Tax percent...")]

        public Nullable<double> Tax { get; set; }
    }
}

MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index(FormCollection form)
        {
            //checking whether admin logged IN or not
            string uname = form["uid"];
            string password = form["pass"];

            if (uname == "admin" && password == "admin")
            {
                return Redirect("ItemList/Index");
            }
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC/Controllers/ItemListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using MVC.Models;

namespace MVC.Controllers
{
    public class ItemListController : Controller
    {
        // Fetch all list of inventory items
        public ActionResult Index()
        {
            IEnumerable<mvcItems> itemList;
            //call API to get Item lists
            HttpResponseMessage response = GlobalVariables.webClient.GetAsync("ItemLists/GetItemList").Result;
            itemList = response.Content.ReadAsAsync<IEnumerable<mvcItems>>().Result;
            return View(itemList);
        }

        //To add/edit item by passing item ID
        public ActionResult AddOrEditItem(int id=0)
        {
            if (id == 0)
                return View(new mvcItems());
            else
            {
                //call API by passing Item id
                HttpResponseMessage reponse = GlobalVariables.webClient.GetAsync("ItemLists/GetItem/"+id.ToString()).Result;
                return View(reponse.Content.ReadAsAsync<mvcItems>().Result);
            }
        }

        //Post method to Save or update Items
        [HttpPost]
        public ActionResult AddOrEditItem(mvcItems items)
        {
            //if item is not available the add else update by calling API
            if (items.ItemID == 0)
            {
                HttpResponseMessage reponse = GlobalVariables.webClient.PostAsJsonAsync("ItemLists/PostItem", items).Result;
                TempData["SuccessMessge"] = "Saved Successfully";
            }
            else {
                HttpResponseMessage reponse = GlobalVariables.webClient.PutAsJsonAsync("ItemLists/PutItem/"+items.ItemID, items).Result;
                TempData["SuccessMessge"] = "Updated Successfully";
            }
            return RedirectToAction("Index");

        }

        //Call to delete Item from list
        public ActionResult Delete(int id)
        {
            //Call API and pass Id of item to delete item
            HttpResponseMessage reponse = GlobalVariables.webClient.DeleteAsync("ItemLists/DeleteItem/" + id.ToString()).Result;
            TempData["SuccessMessge"] = "Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Login Page";
}

@*<div class="jumbotron">
        <h1>ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@


<h2>Login Page</h2>
<hr />
@using (Html.BeginForm())
{
    @Html.Label("UserName");
    @Html.TextBox("uid");
    <br />
    <br />
    @Html.Label("Password");
    @Html.TextBox("pass");
    <br />
    <br />
    <input type="submit" value="Login" id="sb1" name="sb1" />
}

MVC/Views/ItemList/AddOrEditItem.cshtml
@model MVC.Models.mvcItems
@{
    ViewBag.Title = "AddOrEditItem";
}

<div class="form-body">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.ItemID)

        <div class="form-group">
            @Html.LabelFor(model => model.ItemCode)
            @Html.EditorFor(model => model.ItemCode)
            @Html.ValidationMessageFor(model => model.ItemCode)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ItemName)
            @Html.EditorFor(model => model.ItemName)
            @Html.ValidationMessageFor(model => model.ItemName)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Price)
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description)
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Tax)
            @Html.EditorFor(model => model.Tax)
            @Html.ValidationMessageFor(model => model.Tax)
        </div>

        <div class="form-group">
            <input type="submit" value="Submit" class="btn button" />
            <input type="reset" value="Reset" class="btn button" />
        </div>
    }
</div>

@section scripts{
        @Scripts.Render("~/bundles/jqueryval"); 
    }

MVC/Views/ItemList/Index.cshtml
@model IEnumerable<MVC.Models.mvcItems>

@{
    ViewBag.Title = "Index";
}


<p>
   <a href="@Url.Action("AddOrEditItem","ItemList")" class="btn btn-default" >Create Item</a>
</p>
<table class="table">
    <tr>
         
        <th>
            @Html.DisplayNameFor(model => model.ItemCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tax)
        </th>
        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ItemCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tax)
        </td>
        <td>
            <a href="@Url.Action("AddOrEditItem","ItemList",new { id = item.ItemID})" class="btn btn-default" >Edit Item</a>
            <a onclick="Delete(@item.ItemID)" class="btn btn-default" >Delete Item</a>
        </td>
    </tr>
}

</table>


@section scripts{
    <script>
        $(function () {
            var successMsg = '@TempData["SuccessMessage"]'
            if (successMsg != '')
                alertify.success(successMsg);
        });

        function Delete(id) {
            alertify.confirm('Web API with Inventory', 'Are you sure to delete ?', function () {
                window.location.href = '@Url.Action("Delete", "ItemList")/'+id;
            },null);
        }
    </script>
    } 

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

<link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
<link href="~/Content/alertifyjs/themes/default.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inventory", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy;Web API with Inventory</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
<script src="~/Scripts/alertify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>